### ISSUE TITLE
`build.zip` not uploaded for release 1.7.9

### ISSUE THREAD

**Issue by jdblischak** [abbvie-external/OmicNavigatorWebApp#104]
@paulnordlund Did you do something different when you published the v1.7.9 release? The workflow to build and upload `build.zip` expects `GITHUB_REF` to refer to a tag.

For example, the [workflow triggered by the previous v1.7.8 release](https://github.com/abbvie-external/OmicNavigatorWebApp/actions/runs/3896617710/jobs/6653372305) has the following at the beginning, which confirms it was triggered by a tag:

```sh
Job defined at: abbvie-external/OmicNavigatorWebApp/.github/workflows/release.yml@refs/tags/v1.7.8
```

However, this most recent [workflow triggered for the v1.7.9 release](https://github.com/abbvie-external/OmicNavigatorWebApp/actions/runs/3940597316/jobs/6741911280) has the following line pointing to a commit:

```sh
Job defined at: abbvie-external/OmicNavigatorWebApp/.github/workflows/release.yml@b7f5214a721df7f0e90308682190612773e3eb91
```

Note: click on "View raw logs" to see the line I am referring to. I can't link to the raw logs because it is a temporary link that expires

**Comment by paulnordlund** [comment]
I don't think anything was out of the ordinary. Should I try another release?

**Comment by paulnordlund** [comment]
Ok, I've deleted the last, and re-published...we'll see

**Comment by jdblischak** [comment]
Yep, that worked! Whatever you did the second time properly assigned the release to the tag
