### ISSUE TITLE
Set analysis error

### ISSUE THREAD

**Issue by agalperina** [abbvie-external/OmicNavigatorWebApp#48]
App: v1.1.8Package: v1.3.1

This message appears sometimes when you turn set-analysis off.

<img width="668" alt="Screenshot 2021-07-06 152403" src="https://user-images.githubusercontent.com/70035610/124791794-60bbdb80-df1a-11eb-85a4-0647c79734b7.png">

**Comment by ternst23** [comment]
This issue has been fixed by commit e60eccf0c435e9f60aa646d5404a843cfec578a6.
