### ISSUE TITLE
Table with features and related data on Multifeature plot window

### ISSUE THREAD

**Issue by curadomr** [abbvie-external/OmicNavigatorWebApp#55]
For multifeature plots, we first need to select features in the main window's table, and then click on the "multifeature plot" button, located roughly in the center of the main window. Then one can see the plot in a second window, but on this second window the table with features is not available. I'd suggest having the features (and related results) table also present in the window of the multifeature plot, so users can more quickly choose features and immediately see the plot in the same page. 
As it currently stands, one need to go back to the main page to choose new features and then update the multifeature plot. 
Thanks!

- App: v1.2.1
- Package: v1.5.1

**Comment by paulnordlund** [comment]
@bengalengel feature has been approved and released in web app v1.4.0
