### ISSUE TITLE
feature ID warning message

### ISSUE THREAD

**Issue by agalperina** [abbvie-external/OmicNavigatorWebApp#57]
It would be great to get a warning message when the feature IDs of the assay table do not match the feature IDs in the feature table.

**Comment by jdblischak** [comment]
@agalperina Could you please provide an example or some more context where this issue arose? At what step did you expect to see a warning? When a study package is created, OmicNavigator validates that all the feature IDs in the assays table are present in the features table.

**Comment by agalperina** [comment]
@jdblischak in a recent study I came across a scenario where the IDs in the assay and features tables were different. The study uploaded successfully but I think it might be nice to get a warning message when you are installing a study that lets the uploader know that the IDs do not match.

**Comment by jdblischak** [comment]
Bug fixed in https://github.com/abbvie-external/OmicNavigator/commit/260f71d61ce770f5a89ced0fccb6a670a88bf66d. Now `addAssays()` will throw an error if any of the assays tables has a non-numeric column.

Thanks @agalperina for the bug report!
